// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRmt7ADLsLD9RDH2OSMZmrtNVC5LmCxI',
    appId: '1:288902298770:web:c25dbe884c8ee673edfa4b',
    messagingSenderId: '288902298770',
    projectId: 'mobile-modul-6-5fc2c',
    authDomain: 'mobile-modul-6-5fc2c.firebaseapp.com',
    storageBucket: 'mobile-modul-6-5fc2c.firebasestorage.app',
    measurementId: 'G-R1RRXBX0GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXXZMdvTsV9SMLkuJWEPdOwhhl9agETrU',
    appId: '1:288902298770:android:cc8d252c40e28df2edfa4b',
    messagingSenderId: '288902298770',
    projectId: 'mobile-modul-6-5fc2c',
    storageBucket: 'mobile-modul-6-5fc2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2iSsA4tLOjeA7ugzO1BDJV_nv5O3bs8g',
    appId: '1:288902298770:ios:55c454ee815b6487edfa4b',
    messagingSenderId: '288902298770',
    projectId: 'mobile-modul-6-5fc2c',
    storageBucket: 'mobile-modul-6-5fc2c.firebasestorage.app',
    iosBundleId: 'com.example.modul4baru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2iSsA4tLOjeA7ugzO1BDJV_nv5O3bs8g',
    appId: '1:288902298770:ios:55c454ee815b6487edfa4b',
    messagingSenderId: '288902298770',
    projectId: 'mobile-modul-6-5fc2c',
    storageBucket: 'mobile-modul-6-5fc2c.firebasestorage.app',
    iosBundleId: 'com.example.modul4baru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjRmt7ADLsLD9RDH2OSMZmrtNVC5LmCxI',
    appId: '1:288902298770:web:7b21079fde828af3edfa4b',
    messagingSenderId: '288902298770',
    projectId: 'mobile-modul-6-5fc2c',
    authDomain: 'mobile-modul-6-5fc2c.firebaseapp.com',
    storageBucket: 'mobile-modul-6-5fc2c.firebasestorage.app',
    measurementId: 'G-C5X3944ZBG',
  );
}
